### ISSUE TITLE
Thanks for your great work, I'd like to konw how to get the data with carla 0.9.6

### ISSUE THREAD

**Issue by raozhongyu** [twsq/sam-driving#2]
Thanks for your great work, I'd like to konw how to get the data with carla 0.9.6

**Comment by raozhongyu** [comment]
Could you give the example of the dataset with carla 0.8.4

**Comment by twsq** [comment]
To get the data with CARLA 0.9.6, it may be worth taking a look at [https://github.com/dotchen/LearningByCheating], which provides code for collecting data in CARLA 0.9.6. Note that the code in this repository is designed to be used with CARLA 0.8.4, so some modifications may be necessary, especially for the evaluation of the driving model.

Regarding releasing the dataset with CARLA 0.8.4, the full dataset is quite large, which makes it difficult to release. The CARLA 0.8.4 data collector linked to in this repo can be used to collect a similar dataset.

**Comment by raozhongyu** [comment]
Thanks for your reply. I will try it
